### PR TITLE
JBRes-2166 Instances-Level Algorithm

### PR DESCRIPTION
**Pull request by khbminus**
https://youtrack.jetbrains.com/issue/JBRes-2206/Instance-level-Stage
## Description

- Refactored `Function*Lens` and `PsiDDItem` to make it more generic to adopt to different operations on the PSI
- Added a new stage that tries to delete the *functions*, *properties*, *classes*, *objects* 

### Automated tests

Unit tests: `CompressingPsiTrieTest.kt`, `MinimizationPsiManagerDeletablePsiTest.kt`.

Integration tests: `PsiTrieDeletionTest.kt`

### Manual tests

If it's impossible to provide the automated tests, please provide a description of how to verify the changes manually. 

## Self-check list

- [x] PR **title** and **description** are clear and aligned with a format.
- [x] I've added enough **comments** to my code, particularly in hard-to-understand areas. 
- [x] The functionality I've repaired, changed or added is covered with **automated tests**.
- [ ] **Manual tests** have been provided _optionally_.
- [x] The **documentation** for the functionality I've been working on is up-to-date/provided.
- [x] The **link** to this PR is commented on in the corresponding **YT ticket**.

Hint: [x] is a marked item

### CODE REVIEW

**Comment by SBOne-Kenobi** [comment]
Let's try to merge #22 firstly, I will look tho

**Comment by khbminus** [comment]
FYI: this PR has the same bug, as #22. We need to add document committing and disable caches before merging

**Comment by SBOne-Kenobi** [comment]
I think we can postpone this feature for a while because I found out some important stuff that we should do before.
See [JBRes-2246](https://youtrack.jetbrains.com/issue/JBRes-2246) Clean Imports

**Comment by khbminus** [comment]
Yea, the imports are important. Moreover, I'll be needed to oversee the imports when doing the slicing

**Pull request closed without merging**
